# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cclerc/stremio-shell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cclerc/stremio-shell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cclerc/stremio-shell/CMakeFiles /Users/cclerc/stremio-shell//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cclerc/stremio-shell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stremio

# Build rule for target.
stremio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stremio
.PHONY : stremio

# fast build rule for target.
stremio/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/build
.PHONY : stremio/fast

#=============================================================================
# Target rules for targets named stremio_autogen_timestamp_deps

# Build rule for target.
stremio_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stremio_autogen_timestamp_deps
.PHONY : stremio_autogen_timestamp_deps

# fast build rule for target.
stremio_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio_autogen_timestamp_deps.dir/build.make CMakeFiles/stremio_autogen_timestamp_deps.dir/build
.PHONY : stremio_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named stremio_autogen

# Build rule for target.
stremio_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stremio_autogen
.PHONY : stremio_autogen

# fast build rule for target.
stremio_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio_autogen.dir/build.make CMakeFiles/stremio_autogen.dir/build
.PHONY : stremio_autogen/fast

#=============================================================================
# Target rules for targets named SingleApplication

# Build rule for target.
SingleApplication: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SingleApplication
.PHONY : SingleApplication

# fast build rule for target.
SingleApplication/fast:
	$(MAKE) $(MAKESILENT) -f deps/singleapplication/CMakeFiles/SingleApplication.dir/build.make deps/singleapplication/CMakeFiles/SingleApplication.dir/build
.PHONY : SingleApplication/fast

#=============================================================================
# Target rules for targets named SingleApplication_autogen_timestamp_deps

# Build rule for target.
SingleApplication_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SingleApplication_autogen_timestamp_deps
.PHONY : SingleApplication_autogen_timestamp_deps

# fast build rule for target.
SingleApplication_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f deps/singleapplication/CMakeFiles/SingleApplication_autogen_timestamp_deps.dir/build.make deps/singleapplication/CMakeFiles/SingleApplication_autogen_timestamp_deps.dir/build
.PHONY : SingleApplication_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named SingleApplication_autogen

# Build rule for target.
SingleApplication_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SingleApplication_autogen
.PHONY : SingleApplication_autogen

# fast build rule for target.
SingleApplication_autogen/fast:
	$(MAKE) $(MAKESILENT) -f deps/singleapplication/CMakeFiles/SingleApplication_autogen.dir/build.make deps/singleapplication/CMakeFiles/SingleApplication_autogen.dir/build
.PHONY : SingleApplication_autogen/fast

autoupdater.o: autoupdater.cpp.o
.PHONY : autoupdater.o

# target to build an object file
autoupdater.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/autoupdater.cpp.o
.PHONY : autoupdater.cpp.o

autoupdater.i: autoupdater.cpp.i
.PHONY : autoupdater.i

# target to preprocess a source file
autoupdater.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/autoupdater.cpp.i
.PHONY : autoupdater.cpp.i

autoupdater.s: autoupdater.cpp.s
.PHONY : autoupdater.s

# target to generate assembly for a file
autoupdater.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/autoupdater.cpp.s
.PHONY : autoupdater.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/main.cpp.s
.PHONY : main.cpp.s

mpv.o: mpv.cpp.o
.PHONY : mpv.o

# target to build an object file
mpv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/mpv.cpp.o
.PHONY : mpv.cpp.o

mpv.i: mpv.cpp.i
.PHONY : mpv.i

# target to preprocess a source file
mpv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/mpv.cpp.i
.PHONY : mpv.cpp.i

mpv.s: mpv.cpp.s
.PHONY : mpv.s

# target to generate assembly for a file
mpv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/mpv.cpp.s
.PHONY : mpv.cpp.s

qclipboardproxy.o: qclipboardproxy.cpp.o
.PHONY : qclipboardproxy.o

# target to build an object file
qclipboardproxy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/qclipboardproxy.cpp.o
.PHONY : qclipboardproxy.cpp.o

qclipboardproxy.i: qclipboardproxy.cpp.i
.PHONY : qclipboardproxy.i

# target to preprocess a source file
qclipboardproxy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/qclipboardproxy.cpp.i
.PHONY : qclipboardproxy.cpp.i

qclipboardproxy.s: qclipboardproxy.cpp.s
.PHONY : qclipboardproxy.s

# target to generate assembly for a file
qclipboardproxy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/qclipboardproxy.cpp.s
.PHONY : qclipboardproxy.cpp.s

razerchroma.o: razerchroma.cpp.o
.PHONY : razerchroma.o

# target to build an object file
razerchroma.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/razerchroma.cpp.o
.PHONY : razerchroma.cpp.o

razerchroma.i: razerchroma.cpp.i
.PHONY : razerchroma.i

# target to preprocess a source file
razerchroma.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/razerchroma.cpp.i
.PHONY : razerchroma.cpp.i

razerchroma.s: razerchroma.cpp.s
.PHONY : razerchroma.s

# target to generate assembly for a file
razerchroma.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/razerchroma.cpp.s
.PHONY : razerchroma.cpp.s

screensaver.o: screensaver.cpp.o
.PHONY : screensaver.o

# target to build an object file
screensaver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/screensaver.cpp.o
.PHONY : screensaver.cpp.o

screensaver.i: screensaver.cpp.i
.PHONY : screensaver.i

# target to preprocess a source file
screensaver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/screensaver.cpp.i
.PHONY : screensaver.cpp.i

screensaver.s: screensaver.cpp.s
.PHONY : screensaver.s

# target to generate assembly for a file
screensaver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/screensaver.cpp.s
.PHONY : screensaver.cpp.s

stremio_autogen/EWIEGA46WW/qrc_qml.o: stremio_autogen/EWIEGA46WW/qrc_qml.cpp.o
.PHONY : stremio_autogen/EWIEGA46WW/qrc_qml.o

# target to build an object file
stremio_autogen/EWIEGA46WW/qrc_qml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/stremio_autogen/EWIEGA46WW/qrc_qml.cpp.o
.PHONY : stremio_autogen/EWIEGA46WW/qrc_qml.cpp.o

stremio_autogen/EWIEGA46WW/qrc_qml.i: stremio_autogen/EWIEGA46WW/qrc_qml.cpp.i
.PHONY : stremio_autogen/EWIEGA46WW/qrc_qml.i

# target to preprocess a source file
stremio_autogen/EWIEGA46WW/qrc_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/stremio_autogen/EWIEGA46WW/qrc_qml.cpp.i
.PHONY : stremio_autogen/EWIEGA46WW/qrc_qml.cpp.i

stremio_autogen/EWIEGA46WW/qrc_qml.s: stremio_autogen/EWIEGA46WW/qrc_qml.cpp.s
.PHONY : stremio_autogen/EWIEGA46WW/qrc_qml.s

# target to generate assembly for a file
stremio_autogen/EWIEGA46WW/qrc_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/stremio_autogen/EWIEGA46WW/qrc_qml.cpp.s
.PHONY : stremio_autogen/EWIEGA46WW/qrc_qml.cpp.s

stremio_autogen/mocs_compilation.o: stremio_autogen/mocs_compilation.cpp.o
.PHONY : stremio_autogen/mocs_compilation.o

# target to build an object file
stremio_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/stremio_autogen/mocs_compilation.cpp.o
.PHONY : stremio_autogen/mocs_compilation.cpp.o

stremio_autogen/mocs_compilation.i: stremio_autogen/mocs_compilation.cpp.i
.PHONY : stremio_autogen/mocs_compilation.i

# target to preprocess a source file
stremio_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/stremio_autogen/mocs_compilation.cpp.i
.PHONY : stremio_autogen/mocs_compilation.cpp.i

stremio_autogen/mocs_compilation.s: stremio_autogen/mocs_compilation.cpp.s
.PHONY : stremio_autogen/mocs_compilation.s

# target to generate assembly for a file
stremio_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/stremio_autogen/mocs_compilation.cpp.s
.PHONY : stremio_autogen/mocs_compilation.cpp.s

stremioprocess.o: stremioprocess.cpp.o
.PHONY : stremioprocess.o

# target to build an object file
stremioprocess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/stremioprocess.cpp.o
.PHONY : stremioprocess.cpp.o

stremioprocess.i: stremioprocess.cpp.i
.PHONY : stremioprocess.i

# target to preprocess a source file
stremioprocess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/stremioprocess.cpp.i
.PHONY : stremioprocess.cpp.i

stremioprocess.s: stremioprocess.cpp.s
.PHONY : stremioprocess.s

# target to generate assembly for a file
stremioprocess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/stremioprocess.cpp.s
.PHONY : stremioprocess.cpp.s

systemtray.o: systemtray.cpp.o
.PHONY : systemtray.o

# target to build an object file
systemtray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/systemtray.cpp.o
.PHONY : systemtray.cpp.o

systemtray.i: systemtray.cpp.i
.PHONY : systemtray.i

# target to preprocess a source file
systemtray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/systemtray.cpp.i
.PHONY : systemtray.cpp.i

systemtray.s: systemtray.cpp.s
.PHONY : systemtray.s

# target to generate assembly for a file
systemtray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/systemtray.cpp.s
.PHONY : systemtray.cpp.s

verifysig.o: verifysig.c.o
.PHONY : verifysig.o

# target to build an object file
verifysig.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/verifysig.c.o
.PHONY : verifysig.c.o

verifysig.i: verifysig.c.i
.PHONY : verifysig.i

# target to preprocess a source file
verifysig.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/verifysig.c.i
.PHONY : verifysig.c.i

verifysig.s: verifysig.c.s
.PHONY : verifysig.s

# target to generate assembly for a file
verifysig.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stremio.dir/build.make CMakeFiles/stremio.dir/verifysig.c.s
.PHONY : verifysig.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SingleApplication_autogen"
	@echo "... SingleApplication_autogen_timestamp_deps"
	@echo "... stremio_autogen"
	@echo "... stremio_autogen_timestamp_deps"
	@echo "... SingleApplication"
	@echo "... stremio"
	@echo "... autoupdater.o"
	@echo "... autoupdater.i"
	@echo "... autoupdater.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mpv.o"
	@echo "... mpv.i"
	@echo "... mpv.s"
	@echo "... qclipboardproxy.o"
	@echo "... qclipboardproxy.i"
	@echo "... qclipboardproxy.s"
	@echo "... razerchroma.o"
	@echo "... razerchroma.i"
	@echo "... razerchroma.s"
	@echo "... screensaver.o"
	@echo "... screensaver.i"
	@echo "... screensaver.s"
	@echo "... stremio_autogen/EWIEGA46WW/qrc_qml.o"
	@echo "... stremio_autogen/EWIEGA46WW/qrc_qml.i"
	@echo "... stremio_autogen/EWIEGA46WW/qrc_qml.s"
	@echo "... stremio_autogen/mocs_compilation.o"
	@echo "... stremio_autogen/mocs_compilation.i"
	@echo "... stremio_autogen/mocs_compilation.s"
	@echo "... stremioprocess.o"
	@echo "... stremioprocess.i"
	@echo "... stremioprocess.s"
	@echo "... systemtray.o"
	@echo "... systemtray.i"
	@echo "... systemtray.s"
	@echo "... verifysig.o"
	@echo "... verifysig.i"
	@echo "... verifysig.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

